// @version=5
strategy("a", overlay=true,  initial_capital = 1000.0, process_orders_on_close = false, default_qty_type = strategy.percent_of_equity, default_qty_value = 100)

if bar_index == 2100
    strategy.entry("entry long", strategy.long)
if bar_index == 2150
    strategy.close("entry long")

if bar_index == 2150
    strategy.entry("entry long", strategy.long)
if bar_index == 2300
    strategy.close("entry long")

if bar_index == 2310
    strategy.entry("entry short", strategy.short)
if bar_index == 2400
    strategy.close("entry short")

if bar_index == 2410
    strategy.entry("entry short", strategy.short)
if bar_index == 2500
    strategy.close("entry short")

if bar_index == 2550
    strategy.entry("entry long", strategy.long)
if bar_index == 2600
    strategy.entry("entry short", strategy.short)
if bar_index == 2700
    strategy.close("entry short")

if bar_index == 2800
    strategy.entry("entry short", strategy.short)
if bar_index == 2850
    strategy.entry("entry long", strategy.long)
if bar_index == 2900
    strategy.close("entry long")

plot(volume, title='volume', display = display.none)
plot(bar_index, title='bar_index', display = display.none)
plot(strategy.position_size, title='position_size', display = display.none)
plot(strategy.equity, title='equity', display = display.none)
plot(strategy.netprofit, title='net_profit', display = display.none)
plot(strategy.openprofit, title='open_profit', display = display.none)
plot(strategy.opentrades, title='open_trades', display = display.none)
plot(strategy.closedtrades, title='closed_trades', display = display.none)
plot(strategy.grossloss, title='gross_loss', display = display.none)
plot(strategy.grossprofit, title='gross_profit', display = display.none)
plot(strategy.wintrades, title='winning_trades', display = display.none)
plot(strategy.losstrades, title='losing_trades', display = display.none)
